spring.datasource: 
   url: jdbc:mysql://127.0.0.1:3306/zzw01?useSSL=false&serverTimezone=CST
   username: zzw01
   password: 1234
   
   
# 修改运行时的端口号，因为一个端口号只能被一个人使用。
# 如果多个人使用一台服务器，自然要使用不同的端口！
server.port: 8036